language: ruby
rvm: 2.0.0

before_install:
- sudo apt-get install libgif-dev
- npm install -g grunt-cli

bundler_args: --without development --deployment

before_script:
- cd dashboard; bin/rake db:create db:schema:load; cd ..
- cd apps; npm install; grunt build; cd ..

script:
- cd dashboard; bin/rake; cd ..
- cd apps; npm test; cd ..

env:
  global:
  - DB=mysql
  - RAILS_ENV=test
